name: tfsec

on:
  push:
    branches: [ "prod", "staging", "dev" ]
  pull_request:
    branches: [ "prod", "staging", "dev" ]

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
